#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

sudo apt-get update && sudo apt-get upgrade
sudo apt-get -y install haproxy
sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}

echo  "
listen 20205-lb-01
	bind *:80
	balance roundrobin 
	server 11916-web-01 35.173.35.145 check 
    server 11916-zebbyG-02 44.200.109.147 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart
