#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.6
apt-get -y update
apt-get -y install haproxy=2.6.\*
echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 11916-web-01 35.173.35.145:80 check\n\tserver 11916-web-02 44.200.109.147:80 check" >> /etc/haproxy/haproxy.cfg
service haproxy restart
