#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get -y update
apt-get -y install haproxy=2.0.\*
echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 11916-web-01 35.173.35.145 check\n\tserver 11916-web-02 3.236.225.242 check" >> /etc/haproxy/haproxy.cfg
service haproxy restart
